name: renterii
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-144.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  equatable: ^2.0.3
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.10
  animation_wrappers: ^3.0.0
  flutter_rating_bar: ^4.0.0
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  auto_route: ^4.2.1
  image_picker: ^0.8.5+3
  phone_form_field: ^7.0.1
  circle_flags: ^0.0.3
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.1
  geolocator: ^9.0.1
  dio: ^4.0.6
  bloc_concurrency: ^0.2.0
  flutter_svg: ^1.1.4
  http: ^0.13.5
  flutter_stripe: ^4.0.0
  firebase_storage: ^10.3.7
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  flutter_easyloading: ^3.0.5
  number_display: ^3.0.0
#  bitmap: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  auto_route_generator: ^4.2.1
  build_runner:

  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf
  assets:
    - images/
    - images/footermenu/
    - images/account/
    - images/address/
    - images/icons/
    - images/payment/
    - images/Restaurants/
    - images/Banners/
    - images/Food images/
